### ISSUE TITLE
[Frontend] Create the repo and initial folder/file structure for the frontend logic

### ISSUE THREAD

**Issue by amritank** [arturoa925/knowitforward#4]
We need a repo that will hold the react frontend logic. The repo files should be created by running `npm create vite` and must have the below folder structure:

- [ ] package.json
- [ ] index.html
- [ ] src/main.jsx
- [ ] src/index.css
- [ ] src/App.jsx
- [ ] src/App.css
- [ ] src/pages
- [ ] src/components
- [ ] src/assets
- [ ] public
- [ ] The folder should remove most of the boiler plate that gets added as result for npm create vite and just hold the required code to start the server.
- [ ] npm run dev - should start the react server.

**Comment by egodschalk** [comment]
Moved to front end repo https://github.com/kalisurf3r/knowitforward-frontend/issues/2
